import keywordfunction as kf

data = []
data1 = "Avengers: Endgame is a 2019 American superhero film based on the Marvel Comics superhero team the Avengers, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the sequel to 2012's The Avengers, 2015's Avengers: Age of Ultron, and 2018's Avengers: Infinity War, and the 22nd film in the Marvel Cinematic Universe (MCU). It was directed by Anthony and Joe Russo, written by Christopher Markus and Stephen McFeely and features an ensemble cast including Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Brie Larson, Karen Gillan, Danai Gurira, Bradley Cooper, and Josh Brolin. In the film, the surviving members of the Avengers and their allies work together to reverse the damage caused by Thanos in Infinity War.The film was announced in October 2014 as Avengers: Infinity War – Part 2. The Russo brothers came on board to direct in April 2015, and by May, Markus and McFeely signed on to script the film. In July 2016, Marvel removed the title, referring to it simply as Untitled Avengers film. Filming began in August 2017 at Pinewood Atlanta Studios in Fayette County, Georgia, shooting back-to-back with Infinity War, and ended in January 2018. Additional filming took place in the Metro and Downtown Atlanta areas and New York. The official title was revealed in December 2018. With an estimated budget of $356 million, it is the third-most expensive film ever made.Avengers: Endgame was highly anticipated, and Disney backed the film with extensive marketing campaigns. It premiered in Los Angeles on April 22, 2019, and was theatrically released in the United States on April 26, 2019, in IMAX and 3D. The film received praise for its direction, acting, musical score, visual effects and emotional weight, with critics lauding its culmination of the 22-film story. It also broke numerous box office records and has grossed over $2.6 billion worldwide, surpassing Infinity War's entire theatrical run in just 11 days and becoming the highest-grossing film of 2019 and the highest-grossing superhero film ever, as well as the second-highest-grossing film of all time."
data2 = "Captain America: Civil War is a 2016 American superhero film based on the Marvel Comics character Captain America, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the sequel to 2011's Captain America: The First Avenger and 2014's Captain America: The Winter Soldier, and the thirteenth film in the Marvel Cinematic Universe (MCU). The film is directed by Anthony and Joe Russo, with a screenplay by the writing team of Christopher Markus and Stephen McFeely, and stars Chris Evans as Steve Rogers / Captain America, alongside an ensemble cast including Robert Downey Jr., Scarlett Johansson, Sebastian Stan, Anthony Mackie, Don Cheadle, Jeremy Renner, Chadwick Boseman, Paul Bettany, Elizabeth Olsen, Paul Rudd, Emily VanCamp, Tom Holland, Frank Grillo, William Hurt, and Daniel Brühl. In Captain America: Civil War, disagreement over international oversight of the Avengers fractures them into opposing factions—one led by Steve Rogers and the other by Tony Stark.Development of Civil War began in late 2013 when Markus and McFeely began writing the screenplay, which borrows concepts from the 2006 comic book storyline Civil War, while also focusing on story and character elements from the previous Captain America films to conclude the trilogy. Following positive reactions to test screenings of The Winter Soldier, the Russo brothers were brought back to direct in early 2014. The film's title and premise were revealed in October 2014, along with Downey's casting; additional cast members joined in the following months. Principal photography began in April 2015 at Pinewood Atlanta Studios in Fayette County, Georgia, and continued in the Metro Atlanta area before concluding in Germany in August 2015, with the film being the first to use IMAX's digital 2D cameras (for the film's central airport fight sequence). Visual effects were provided by nearly 20 different studios during the post-production process.Captain America: Civil War held its world premiere in Los Angeles on April 12, 2016, and was released in the United States on May 6, 2016, in 3D and IMAX 3D. The film was a critical and commercial success, grossing over $1.1 billion worldwide, and garnering praise for the performances (particularly Evans and Downey), action, screenplay, and themes. It became the highest-grossing film of 2016 and the twelfth-highest-grossing film of all time"

data.append(data1)
data.append(data2)

r = kf.keywordfunction(data)
print(r.MakeKeyword())